// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var PostsQuery$ReactHooksTemplate = require("./PostsQuery.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Hello"), React.createElement(PostsQuery$ReactHooksTemplate.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
