// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReactHooks = require("@apollo/react-hooks");
var App$ReactHooksTemplate = require("./App.bs.js");
var GraphQLClient$ReactHooksTemplate = require("./GraphQLClient.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ReactHooks.ApolloProvider, {
          client: GraphQLClient$ReactHooksTemplate.instance,
          children: React.createElement(App$ReactHooksTemplate.make, { })
        }), "root");

/*  Not a pure module */
